server:
  port: 7777
  servlet:
    session:
      cookie:
        name: oauth_session
spring:
  application:
    name: server-oauth-simplejwt
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

logging:
  level:
    root: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG