
spring:
  application:
    name: db-creater
#  jpa:
#    generate-ddl: false
#    show-sql: true
#    hibernate:
#      ddl-auto: none
  datasource:
    continue-on-error: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdemo?useSSL=false
    username: root
    password: root
    schema: classpath:schema.sql
    initialization-mode: always
server:
  port: 9090