server:
  port: 7778
spring:
  application:
    name: cay-service-user
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
logging:
  level:
    root: debug