spring:
  application:
    name: cay-zuul
server:
  port: 8888
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    first-auth-demo:
      path: /demo/**
      sensitiveHeaders:
      serviceId: cay-service-demo
security:
  oauth2:
    client:
      client-id: myclient
      client-secret: 123
      authentication-scheme: header
      access-token-uri: http://localhost:7777/oauth/token
      user-authorization-uri: http://localhost:7777/oauth/authorize
    resource:
      user-info-uri:  http://localhost:7777/user
      prefer-token-info: false
      jwt:
        key-value: 112233